name: Build `rails-compose` gem

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: glials/rails-compose/.github/workflows/test.yml

      - name: Build gem
        run: gem build rails-compose.gemspec
